-- return {
--     "yetone/avante.nvim",
--     dependencies = {
--         "MunifTanjim/nui.nvim",
--         "nvim-lua/plenary.nvim",
--         "stevearc/dressing.nvim",
--         "nvim-tree/nvim-web-devicons",
--     },
--     config = function()
--         require("avante").setup({})
--     end,
-- } 