local icons = {
	ai = { icon = "󰚩", color = "cyan" },
	action = { icon = "󰌵", color = "yellow" },
	close = { icon = "󰅖", color = "red" },
	file = { icon = "󰈔", color = "azure" },
	fix = { icon = "󰁨", color = "green" },
	jobs = { icon = "󰒋", color = "green" },
	send = { icon = "󰍉", color = "cyan" },
	terminal = { icon = "", color = "blue" },
}

return {
	"folke/which-key.nvim",
	event = "VeryLazy",
	opts = {
		triggers = {
			{ "<leader>c", mode = { "n", "v" } },
			{ "<leader>d", mode = { "n", "v" } },
			{ "<leader>f", mode = { "n", "v", "o" } },
			{ "<leader>h", mode = { "n", "v" } },
			{ "<leader>s", mode = { "n", "v" } },
			{ "<leader>t", mode = { "n", "v" } },
			{ "<leader>w", mode = { "n", "v" } },
			{ "<leader>y", mode = { "n", "v" } },
		},
		plugins = {
			marks = false,
			registers = false,
			spelling = {
				enabled = false,
			},
			presets = {
				operators = false,
				motions = false,
				text_objects = false,
				windows = false,
				nav = false,
				z = false,
				g = false,
			},
		},
		spec = {
			{ "<leader>c", group = "code / ai", icon = icons.ai },
			{ "<leader>ca", desc = "code action", icon = icons.action },
			{ "<leader>cc", desc = "open claude code", icon = icons.ai },
			{ "<leader>cd", desc = "open codex", icon = icons.terminal },
			{ "<leader>cf", desc = "run llm fix", icon = icons.fix, mode = { "n", "v" } },
			{ "<leader>cl", desc = "llm jobs", icon = icons.jobs },
			{ "<leader>cp", desc = "send file path", icon = icons.file },
			{ "<leader>cq", desc = "close ai pane", icon = icons.close },
			{ "<leader>cx", desc = "send line/selection", icon = icons.send, mode = { "n", "v" } },
			{ "<leader>y", group = "yank" },
			{ "<leader>s", group = "search" },
			{ "<leader>t", group = "toggle" },
			{ "<leader>h", group = "git hunks" },
			{ "<leader>w", group = "workspace" },
			{ "<leader>d", group = "diagnostics" },
			{ "<leader>f", group = "treesitter movement" },
		},
	},
}
